CREATE TABLE nft_sales (
  _dbt_source VARCHAR(255),
  chain_name VARCHAR(255),
  chain_id INT64,
  block_id INT64,
  block_height INT64,
  log_offset INT64,
  signed_at DATETIME,
  tx_hash CHAR(32),
  market VARCHAR(255),
  to CHAR(20),
  from
    CHAR(20),
    maker CHAR(20),
    taker CHAR(20),
    token_id DECIMAL(78, 0),
    collection_address CHAR(20),
    collection_name VARCHAR(255),
    token_address CHAR(20),
    token_name VARCHAR(255),
    ticker_symbol VARCHAR(255),
    num_decimals INT64,
    nft_token_price FLOAT64,
    nft_token_price_unscaled DECIMAL(78, 0),
    nft_token_price_usd FLOAT64,
    nft_token_price_native FLOAT64,
    fees_paid_unscaled DECIMAL(78, 0),
    gas_eth FLOAT64,
    gas_usd_price FLOAT64,
    token_count INT64
);